name: XiavicCore
main: Main.mainClass
authors: [Imhandmade, Kerlab, VottusCode]
version: 2.0
commands:
  clear:
    usage:
    description:
  clearall:
    usage:
    description:
  ec:
    usage:
    description:
  feed:
    usage:
    description:
  heal:
    usage:
    description:
  gamemode:
    usage:
    description:
    aliases: gm
  setspawn:
    usage:
    description:
  spawn:
    usage:
    description:
  tpa:
    usage:
    description:
  tpaccept:
    usage:
    description:
  tpdeny:
    usage:
    description:
  rtp:
    usage:
    description:
  argh:
    usage:
    description:
  cheatexp:
    usage:
    description:
  walkspeed:
    usage:
    description:
  flyspeed:
    usage:
    description:
  dispose:
    usage:
    description:
    aliases: trash
  whois:
    usage:
    description:
  cheatarmor:
    usage:
    description:
  coreconfigupdate:
    usage:
    description:
    aliases: ccu
  tp:
    usage:
    description:
  tphere:
    usage:
    description:
  ext:
    usage:
    description:
    aliases: extinguish
  info:
    usage:
    description:
    aliases: iteminfo
  serverinfo:
    usage:
    description:
  coreversion:
    usage:
    description:
    aliases: cv
  fly:
    usage:
    description:
  top:
    usage:
    description:
  pony:
    usage:
    description:
  near:
    usage:
    description:
  forums:
    usage:
    description:
  twitter:
    usage:
    description:
  website:
    usage:
    description:
  youtube:
    usage:
    description:
  discord:
    usage:
    description:
  god:
    usage:
    description:
  back:
    usage:
    description:
  suicide:
    usage:
    description: